stages:
    - build
    - test
    - deploy

build Job:
    stage: build
    script:
        - mkdir -p build
        - cd build && cmake ..
        - cd build && make
    
test Job:
    stage: test
    script:
       - echo "This is the first test job"

deploy Job:
    stage: deploy
    script:
        - scp -r -P 2222 build/git@szofttech.inf.elte.hu:software-technology-2023/group-2/blue-fox.git:/home/user/deployed_game


