image: python:3.8.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pygame==2.4.0
  - pip install pytest

build:
  script:
    - mkdir -p build

test:
  script:
    - export PYTHONPATH="$PYTHONPATH:$CI_PROJECT_DIR"
    - pytest my_game -v



# deploy:
#   stage: deploy
#   script: scp -r -P 2222 build/git@szofttech.inf.elte.hu:software-technology-2023/group-2/blue-fox.git:/home/user/deployed_game
#   environment: production
